### ISSUE TITLE
Installation on Fedora 39 via homebrew failed

### ISSUE THREAD

**Issue by gene-hightower** [NASA-SW-VnV/homebrew-core#11]
gene@digilicious:~$ brew install nasa-sw-vnv/core/ikos
Ignoring hpricot-0.8.6 because its extensions are not built. Try: gem pristine hpricot --version 0.8.6
Ignoring rdiscount-2.2.0.1 because its extensions are not built. Try: gem pristine rdiscount --version 2.2.0.1
Ignoring hpricot-0.8.6 because its extensions are not built. Try: gem pristine hpricot --version 0.8.6
Ignoring rdiscount-2.2.0.1 because its extensions are not built. Try: gem pristine rdiscount --version 2.2.0.1
==> Fetching nasa-sw-vnv/core/ikos
==> Downloading https://files.pythonhosted.org/packages/7e/ae/26808275fc76bf2832deb10d3a3ed3107bc4de01b85dcccbe525f2
Already downloaded: /home/gene/.cache/Homebrew/downloads/6ca94f739e0ce8b61064d8fa84dcd6adf34e71e1a606f1ec9403a187965de88c--Pygments-2.4.2.tar.gz
==> Downloading https://github.com/NASA-SW-VnV/ikos/archive/refs/tags/v3.2.tar.gz
Already downloaded: /home/gene/.cache/Homebrew/downloads/1fe6d9981957abde286f236e44082fb056f93bd4820392065c8fdb673e17dd1d--ikos-3.2.tar.gz
==> Installing ikos from nasa-sw-vnv/core
==> python3 -m venv --system-site-packages --without-pip /home/linuxbrew/.linuxbrew/Cellar/ikos/3.2_1/libexec
==> python3 -m pip --python=/home/linuxbrew/.linuxbrew/Cellar/ikos/3.2_1/libexec/bin/python install /tmp/ikos--Pygme
==> cmake -G Unix Makefiles -DGMP_ROOT=/home/linuxbrew/.linuxbrew/opt/gmp -DMPFR_ROOT=/home/linuxbrew/.linuxbrew/opt
==> make install
Last 15 lines from /home/gene/.cache/Homebrew/Logs/ikos/04.make:
/tmp/ikos-20231228-1110100-ituc05/ikos-3.2/core/include/ikos/core/adt/patricia_tree/set.hpp:892:20: error: ‘ikos::core::patricia_tree_utils::is_zero_bit’ cannot be used as a function
  892 |     if (is_zero_bit(p, n)) {
      |         ~~~~~~~~~~~^~~~~~
[ 21%] Linking CXX static library libikos-pp.a
[ 21%] Built target ikos-pp-lib
[ 21%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/frontend.cpp.o
[ 22%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/type.cpp.o
make[2]: *** [ar/CMakeFiles/ikos-ar.dir/build.make:188: ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_upcast_comparison.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1528: ar/CMakeFiles/ikos-ar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 24%] Linking CXX executable ikos-pp
[ 24%] Built target ikos-pp
make: *** [Makefile:146: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

**Comment by ivanperez-keera** [comment]
Thanks, @gene-hightower . Are you able to upload the full /home/gene/.cache/Homebrew/Logs/ikos/04.make? (I can also give you an email to send it to if that's preferable).

**Comment by gene-hightower** [comment]
[04.make.txt](https://github.com/NASA-SW-VnV/homebrew-core/files/13790069/04.make.txt)
Sure

**Comment by ivanperez-keera** [comment]
I think this was fixed by: https://github.com/NASA-SW-VnV/ikos/issues/273. Could you please try again and re-open this issue if it doesn't work? Thanks!

**Comment by gene-hightower** [comment]
The homebrew install now seems to work, thanks very much.

**Comment by ivanperez-keera** [comment]
Great! Thanks!
