### ISSUE TITLE
Apron `incompatible function pointer type` error on Intel Mac

### ISSUE THREAD

**Issue by Bckempa** [NASA-SW-VnV/homebrew-core#17]
While attempting to install `ikos` via this Homebrew tap on an Intel MacOS 14.4 machine, I received a `incompatible function pointer type` error during the `apron` build.

<details>
<summary>Terminal Output</summary>

```
❯ brew install ikos
<Downloads elided for clarity>
==> Installing ikos from nasa-sw-vnv/core
==> Installing dependencies for nasa-sw-vnv/core/ikos: nasa-sw-vnv/core/apron, llvm@14 and openssl@3
==> Installing nasa-sw-vnv/core/ikos dependency: nasa-sw-vnv/core/apron
==> Patching
==> make APRON_PREFIX=/usr/local/Cellar/apron/0.9.10_1 GMP_PREFIX=/usr/local/opt/gmp MPFR_PREFIX=/usr/local/opt/mpfr P
Last 15 lines from /Users/bckempa/Library/Logs/Homebrew/apron/01.make:
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_representationMPQ.o pk_representation.c
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_approximateMPQ.o pk_approximate.c
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_constructorMPQ.o pk_constructor.c
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_testMPQ.o pk_test.c
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_extractMPQ.o pk_extract.c
clang -Wcast-qual -Wswitch -Werror-implicit-function-declaration -Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wno-unused -std=c99 -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -I/tmp/include -I../apron -I../num -I../itv -I../mlapronidl -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/lib/ocaml -I/usr/lib/ocaml -DNUM_MPQ -I/usr/local/opt/gmp/include -c -o pk_meetjoinMPQ.o pk_meetjoin.c
pk_meetjoin.c:591:9: error: incompatible function pointer types passing 'pk_t *(*)(ap_manager_t *, bool, pk_t *, ap_lincons0_array_t *)' (aka 'struct pk_t *(*)(struct ap_manager_t *, char, struct pk_t *, struct ap_lincons0_array_t *)') to parameter of type 'void *(*)(ap_manager_t *, bool, void *, ap_lincons0_array_t *)' (aka 'void *(*)(struct ap_manager_t *, char, void *, struct ap_lincons0_array_t *)') [-Wincompatible-function-pointer-types]
                                                  &pk_meet_lincons_array);
                                                  ^~~~~~~~~~~~~~~~~~~~~~
../apron/ap_generic.h:87:15: note: passing argument to parameter 'meet_lincons_array' here
                                         void* (*meet_lincons_array)(ap_manager_t*,
                                                 ^
1 error generated.
make[1]: *** [pk_meetjoinMPQ.o] Error 1
make: *** [c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

brew install ikos  29.09s user 10.13s system 90% cpu 43.134 total
```

</details>

**Comment by aogrcs** [comment]
I install Homebrew version 4.3.0 for Ubuntu 20.04, and find error:
make APRON_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/apron/0.9.10_1 GMP_PREFIX=/home/linuxbrew/.linuxbrew/opt/gmp MPFR_PREFIX=/home/linuxbrew/.linuxbrew/opt/mpfr PPL_PREFIX=/home/linuxbrew/.linuxbrew/
Last 15 lines from /home/cocosim/.cache/Homebrew/Logs/apron/01.make:
  591 |                                                   &pk_meet_lincons_array);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *) {aka pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)}
In file included from pk_meetjoin.c:20:
../apron/ap_generic.h:87:50: note: expected 'void * (*)(ap_manager_t *, bool,  void *, ap_lincons0_array_t *)' {aka 'void * (*)(ap_manager_t *, char,  void *, ap_lincons0_array_t *)'} but argument is of type 'pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *)' {aka 'pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)'}
   87 |                                          void* (*meet_lincons_array)(ap_manager_t*,
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                                                                      bool, void*,
      |                                                                      ~~~~~~~~~~~~
   89 |                                                                      ap_lincons0_array_t*));
      |                                                                      ~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:204: pk_meetjoinMPQ.o] Error 1
make[1]: Leaving directory '/tmp/apron-20240515-92736-sv533b/apron-0.9.10/newpolka'
make: *** [Makefile:22: c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

These open issues may also help:
Apron `incompatible function pointer type` error on Intel Mac https://github.com/NASA-SW-VnV/homebrew-core/issues/17

**Comment by aogrcs** [comment]
I install Homebrew version 4.3.0 for Ubuntu 20.04, and find error:
make APRON_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/apron/0.9.10_1 GMP_PREFIX=/home/linuxbrew/.linuxbrew/opt/gmp MPFR_PREFIX=/home/linuxbrew/.linuxbrew/opt/mpfr PPL_PREFIX=/home/linuxbrew/.linuxbrew/
Last 15 lines from /home/cocosim/.cache/Homebrew/Logs/apron/01.make:
  591 |                                                   &pk_meet_lincons_array);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *) {aka pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)}
In file included from pk_meetjoin.c:20:
../apron/ap_generic.h:87:50: note: expected 'void * (*)(ap_manager_t *, bool,  void *, ap_lincons0_array_t *)' {aka 'void * (*)(ap_manager_t *, char,  void *, ap_lincons0_array_t *)'} but argument is of type 'pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *)' {aka 'pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)'}
   87 |                                          void* (*meet_lincons_array)(ap_manager_t*,
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                                                                      bool, void*,
      |                                                                      ~~~~~~~~~~~~
   89 |                                                                      ap_lincons0_array_t*));
      |                                                                      ~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:204: pk_meetjoinMPQ.o] Error 1
make[1]: Leaving directory '/tmp/apron-20240515-92736-sv533b/apron-0.9.10/newpolka'
make: *** [Makefile:22: c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

These open issues may also help:
Apron `incompatible function pointer type` error on Intel Mac https://github.com/NASA-SW-VnV/homebrew-core/issues/17

**Comment by ivanperez-keera** [comment]
I'm looking into this right now.
